### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yungd1plomat**
Readme update, as there is now documentation on a separate site

### CODE REVIEW

**Comment by wherewhere** [comment]
??? Why you remove the example?

**Comment by yungd1plomat** [comment]
> ??? Why you remove the example?

there is a quickstart, the rest of the methods can be found in the documentation
изображение

**Comment by wherewhere** [comment]
Maybe you can leave some vary useful examples like install apk.

**Comment by yungd1plomat** [comment]
> Maybe you can leave some vary useful examples like install apk.

ok

**Pull request closed without merging**
