### PR TITLE
Create better documentation

### PR DESCRIPTION
**Pull request by yungd1plomat**
Sections:
- **About**
    - [x] Introduction
    - [x] Consulting and Support
    - [x] Licence
- **Getting started**
    - [x] Installation
    - [x] Connecting to device
    - [x] Working with lib
- **Reference**
    - Screen automation
        - [ ] Find elements
        - [ ] Click on an element
        - [ ] Swipe
        - [ ] Type text
        - [ ] Send key events
        - [ ] Dump xml hierarchy
        - [ ] Create screenshots
    - Device commands
        - [ ] Install applications
        - [ ] Starting applications
        - [ ] Working with files
        - [ ] Run shell commands
        - [ ] Forward connection
- **Tutorials**
    - [ ] Automate multiple Nox emulators
    

Docs created using [docsify](https://docsify.js.org) and [docsify-darklight-theme](https://docsify-darklight-theme.boopathikumar.me/)

To serve docs use docsify http server
```
# Install docsify
npm i docsify-cli -g

# Serve docs
docsify serve docs
```

Or using any other http servers. Example with python:
```Python
cd docs && python -m SimpleHTTPServer 3000

# OR

cd docs && python -m http.server 3000
```

### CODE REVIEW

**Comment by wherewhere** [comment]
It will be better to have a new repo to write doc.
And repo wiki is here...
https://github.com/SharpAdb/AdvancedSharpAdbClient/wiki

**Comment by yungd1plomat** [comment]
> It will be better to have a new repo to write doc. And repo wiki is here... https://github.com/SharpAdb/AdvancedSharpAdbClient/wiki

i thinks it's ok to have docs here because github pages domain will be AdvancedSharpAdbClient.github.io

**Comment by wherewhere** [comment]
It is better to not use var in document. Using var will make it unclearly.

**Comment by wherewhere** [comment]
> i thinks it's ok to have docs here because github pages domain will be AdvancedSharpAdbClient.github.io

AdvancedSharpAdbClient.Documents.github.io

**Comment by yungd1plomat** [comment]
ok i'll move later

**Pull request closed without merging**
