### PR TITLE
Fix autobuild for organization

### PR DESCRIPTION
**Pull request by yungd1plomat**
After moving the repository to a separate organization, packages need to be published in the same organization packages

### CODE REVIEW

**Comment by yungd1plomat** [comment]
@wherewhere do I need to move the winrt branch to another AdvancedSharpAdbClient.WinRT repository?

**Comment by wherewhere** [comment]
Wow, I will do that.

**Comment by wherewhere** [comment]
um... I am only a member...

**Comment by yungd1plomat** [comment]
> um... I am only a member...

one moment

**Comment by yungd1plomat** [comment]
> um... I am only a member...

done

**Comment by wherewhere** [comment]
I created a nuget organization.
https://www.nuget.org/profiles/SharpAdb

**Comment by wherewhere** [comment]
My VK ID is [@wherewhere7](https://vk.com/wherewhere7). Maybe we can chat on it...

**Comment by yungd1plomat** [comment]
> My VK ID is [@wherewhere7](https://vk.com/wherewhere7). Maybe we can chat on it...
ahha, ok

**Pull request merged**
